package com.example.newdesign.utils

enum class SharedPreferencesKeys {
    PREF_USER_TOKEN, PREF_LANGUAGE_ID, PREF_FCM_TOKEN, PREf_FIRST_USED, PREF_USER_NAME,PREF_USER_ID,PREF_USER_EMAIL,PREF_USER_PHONE,PREF_SUBSCRIBE_ASK,PREF_LANG_NAME
}